---

volumes:
  hazardsets:
  postgresql_data:

services:

  db:
    image: camptocamp/postgres:13-postgis-3
    volumes:
      - ./docker/testdb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD_PUBLIC}
      POSTGRES_DB: ${PGDATABASE_PUBLIC}
      POSTGRES_USER: ${PGUSER_PUBLIC}

  thinkhazard:
    image: camptocamp/thinkhazard
    build: &build
      context: .
      target: app
      args:
        TX_TOKEN: ${TX_TOKEN}
    user: www-data
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - hazardsets:/tmp/hazardsets
    environment: &env
      - INI_FILE
      - TX_TOKEN
      - PGHOST
      - PGPORT
      - PGUSER_PUBLIC
      - PGPASSWORD_PUBLIC
      - PGDATABASE_PUBLIC
      - PGUSER_ADMIN
      - PGPASSWORD_ADMIN
      - PGDATABASE_ADMIN
      - AWS_ENDPOINT_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_BUCKET_NAME
      - GEONODE_URL
      - GEONODE_USERNAME
      - GEONODE_API_KEY
      - ANALYTICS
      - BROKER_URL
      - HTPASSWORDS
    ports:
      - 8080:8080

  taskrunner:
    image: camptocamp/thinkhazard
    build: *build
    user: www-data
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - hazardsets:/tmp/hazardsets
    environment: *env
    command: 'celery -A thinkhazard.celery worker -l info'

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    command: 'minio server /data'

  redis:
    image: redis
    ports:
      - "6379:6379"

  minio-client:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./docker/minio-client/docker-entrypoint:/docker-entrypoint
    environment:
      - AWS_HOST=minio
      - AWS_PORT=9000
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_BUCKET_NAME
    entrypoint: /docker-entrypoint
    command: ["exit", "0"]
