---

services:
  testdb:
    image: camptocamp/postgres:13-postgis-3
    volumes:
      - ./docker/testdb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: thinkhazard
      POSTGRES_DB: thinkhazard_test
      POSTGRES_USER: thinkhazard

  test:
    image: camptocamp/thinkhazard-builder
    build: &build
      context: .
      target: builder
      args:
        TX_TOKEN: ${TX_TOKEN}
    depends_on:
      - testdb
      - testredis
      - testminio-client
    volumes:
      - '${PWD}/thinkhazard:/app/thinkhazard'
      - '${PWD}/tests:/app/tests'
    environment: &env
      - INI_FILE
      - PGHOST=testdb
      - PGPORT=5432
      - PGUSER_PUBLIC=thinkhazard
      - PGPASSWORD_PUBLIC=thinkhazard
      - PGDATABASE_PUBLIC=thinkhazard_test
      - PGUSER_ADMIN=thinkhazard
      - PGPASSWORD_ADMIN=thinkhazard
      - PGDATABASE_ADMIN=thinkhazard_test
      - AWS_ENDPOINT_URL=http://testminio:9000/
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_BUCKET_NAME=thinkhazard
      - GEONODE_API_KEY
      - ANALYTICS
      - BROKER_URL=redis://testredis:6379/0
      - HTPASSWORDS

  testminio:
    image: minio/minio
    command: 'minio server /data'

  testredis:
    image: redis

  testminio-client:
    image: minio/mc
    depends_on:
      - testminio
    volumes:
      - ./docker/minio-client/docker-entrypoint:/docker-entrypoint
    environment:
      - AWS_HOST=testminio
      - AWS_PORT=9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_BUCKET_NAME=thinkhazard
    entrypoint: /docker-entrypoint
    command: ["exit", "0"]
