version: '3'

services:
  thinkhazard:
    image: camptocamp/thinkhazard-builder
    build: &build
      target: builder
    environment:
      USE_CACHE: 'TRUE'
      # PUPPETEER_URL: 'http://localhost:3000'
    volumes:
      - '${PWD}/development.ini:/app/development.ini'
      - '${PWD}/thinkhazard:/app/thinkhazard'
    command: 'pserve --reload c2c://development.ini'

  taskrunner:
    image: camptocamp/thinkhazard-builder
    build: *build
    environment:
      USE_CACHE: 'TRUE'
    volumes:
      - '${PWD}/development.ini:/app/development.ini'
      - '${PWD}/thinkhazard:/app/thinkhazard'

  puppeteer:
    build:
      args:
        NODE_ENV: development
    volumes:
      - ./docker/puppeteer/server.js:/app/server.js
    environment:
      - NODE_ENV=development
    command: npx nodemon --inspect=0.0.0.0:9229 server.js
    ports:
      - "8081:8080"
      - "9229:9229"
