version: '3'

services:
  thinkhazard:
    image: camptocamp/thinkhazard-builder
    build: &build
      target: builder
    environment:
      USE_CACHE: 'TRUE'
      # PUPPETEER_URL: 'http://localhost:3000'
    volumes:
      - '${PWD}/development.ini:/app/development.ini'
      - '${PWD}/thinkhazard:/app/thinkhazard'
    command: 'python3 -m debugpy --listen "0.0.0.0:5678" /usr/local/bin/pserve --reload c2c://development.ini'
    ports:
        - 5678:5678

  taskrunner:
    image: camptocamp/thinkhazard-builder
    build: *build
    environment:
      USE_CACHE: 'TRUE'
    volumes:
      - '${PWD}/development.ini:/app/development.ini'
      - '${PWD}/thinkhazard:/app/thinkhazard'
    command: 'python3 -m debugpy --listen "0.0.0.0:5679" /usr/local/bin/celery -A thinkhazard.celery worker -l info --concurrency=1'
    ports:
      - 5679:5679

  puppeteer:
    build:
      args:
        NODE_ENV: development
    volumes:
      - ./docker/puppeteer/server.js:/app/server.js
    environment:
      - NODE_ENV=development
    command: npx nodemon --inspect=0.0.0.0:9229 server.js
    ports:
      - "8081:8080"
      - "9229:9229"
