---

services:
  testdb:
    image: camptocamp/postgres:13-postgis-3
    volumes:
      - ./docker/testdb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: thinkhazard
      POSTGRES_DB: thinkhazard_test
      POSTGRES_USER: thinkhazard

  test:
    image: camptocamp/thinkhazard-builder
    build: &build
      context: .
      target: builder
      args:
        TX_TOKEN: ${TX_TOKEN}
        TX_BRANCH: ${TX_BRANCH}
    depends_on:
      - testdb
      - testredis
      - tests3
    volumes:
      - '${PWD}/thinkhazard:/app/thinkhazard'
      - '${PWD}/tests:/app/tests'
    environment: &env
      - INI_FILE
      - PGHOST=testdb
      - PGPORT=5432
      - PGUSER_PUBLIC=thinkhazard
      - PGPASSWORD_PUBLIC=thinkhazard
      - PGDATABASE_PUBLIC=thinkhazard_test
      - PGUSER_ADMIN=thinkhazard
      - PGPASSWORD_ADMIN=thinkhazard
      - PGDATABASE_ADMIN=thinkhazard_test
      - AWS_ENDPOINT_URL=http://tests3:9000/
      - AWS_ACCESS_KEY_ID=thinkhazard
      - AWS_SECRET_ACCESS_KEY=thinkhazard
      - AWS_BUCKET_NAME=thinkhazard
      - GEONODE_API_KEY
      - ANALYTICS
      - BROKER_URL=redis://testredis:6379/0
      - HTPASSWORDS
      - PUPPETEER_URL
      - PROTECT_PUBLIC_SITE

  tests3:
    image: andrewgaul/s3proxy
    environment:
      - S3PROXY_ENDPOINT=http://0.0.0.0:9000
      - S3PROXY_AUTHORIZATION=aws-v2-or-v4
      - S3PROXY_IDENTITY=thinkhazard
      - S3PROXY_CREDENTIAL=thinkhazard
      - JCLOUDS_PROVIDER=filesystem
      - JCLOUDS_FILESYSTEM_BASEDIR=/data
      - AWS_BUCKET_NAME=thinkhazard
    entrypoint: ["sh", "-c", 'mkdir -p "/data/$${AWS_BUCKET_NAME}" && exec /opt/s3proxy/run-docker-container.sh']

  testredis:
    image: redis
