"""empty message

Revision ID: b0a2bee1929b
Revises: 
Create Date: 2016-04-01 15:01:13.882785

"""

# revision identifiers, used by Alembic.
revision = 'b0a2bee1929b'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_datamart_rel_hc_ad_ad', 'rel_hazardcategory_administrativedivision', ['administrativedivision_id'], unique=False, schema='datamart')
    op.create_index('ix_datamart_rel_hc_ad_hc', 'rel_hazardcategory_administrativedivision', ['hazardcategory_id'], unique=False, schema='datamart')
    op.drop_index('ix_datamart_rel_hazardcategory_administrativedivision_a_5944', table_name='rel_hazardcategory_administrativedivision', schema='datamart')
    op.drop_index('ix_datamart_rel_hazardcategory_administrativedivision_h_7996', table_name='rel_hazardcategory_administrativedivision', schema='datamart')
    op.create_index('ix_datamart_rel_hc_tr_hc', 'rel_hazardcategory_technicalrecommendation', ['hazardcategory_id'], unique=False, schema='datamart')
    op.create_index('ix_datamart_rel_hc_tr_tc', 'rel_hazardcategory_technicalrecommendation', ['technicalrecommendation_id'], unique=False, schema='datamart')
    op.drop_index('ix_datamart_rel_hazardcategory_technicalrecommendation__abe2', table_name='rel_hazardcategory_technicalrecommendation', schema='datamart')
    op.drop_index('ix_datamart_rel_hazardcategory_technicalrecommendation__ccee', table_name='rel_hazardcategory_technicalrecommendation', schema='datamart')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_datamart_rel_hazardcategory_technicalrecommendation__ccee', 'rel_hazardcategory_technicalrecommendation', ['technicalrecommendation_id'], unique=False, schema='datamart')
    op.create_index('ix_datamart_rel_hazardcategory_technicalrecommendation__abe2', 'rel_hazardcategory_technicalrecommendation', ['hazardcategory_id'], unique=False, schema='datamart')
    op.drop_index('ix_datamart_rel_hc_tr_tc', table_name='rel_hazardcategory_technicalrecommendation', schema='datamart')
    op.drop_index('ix_datamart_rel_hc_tr_hc', table_name='rel_hazardcategory_technicalrecommendation', schema='datamart')
    op.create_index('ix_datamart_rel_hazardcategory_administrativedivision_h_7996', 'rel_hazardcategory_administrativedivision', ['hazardcategory_id'], unique=False, schema='datamart')
    op.create_index('ix_datamart_rel_hazardcategory_administrativedivision_a_5944', 'rel_hazardcategory_administrativedivision', ['administrativedivision_id'], unique=False, schema='datamart')
    op.drop_index('ix_datamart_rel_hc_ad_hc', table_name='rel_hazardcategory_administrativedivision', schema='datamart')
    op.drop_index('ix_datamart_rel_hc_ad_ad', table_name='rel_hazardcategory_administrativedivision', schema='datamart')
    ### end Alembic commands ###
