# Book settings
title: ThinkHazard! Documentation
author: GFDRR ThinkHazard! Project
logo: images/ThinkHazard.png
copyright: "This guide is hosted on github under a public domain license. The original work is a product of GFDRR ThinkHazard! project."

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: thinkhazard-methodology.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/GFDRR/thinkhazard
  path_to_book: docs
  branch: master

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  home_page_in_navbar: true
  baseurl: https://gfdrr.github.io/thinkhazard/

# Sphinx configuration
sphinx:
  extra_extensions:
    - sphinx_design
  config:
    templates_path:
      - _templates
    html_theme_options:
      repository_url: https://github.com/GFDRR/thinkhazard
      use_repository_button: false
      use_issues_button: false
      use_edit_page_button: false
      show_toc_level: 2
      theme_switcher: false
    html_context:
      default_mode: light
    html_css_files:
      - custom.css
    html_static_path:
      - _static
