#!/bin/bash
# Copy JSON files and query builder to _build/html for deployment
# JSON files are in public/, generated by convert_csv_to_json.py
# Query builder is in docs/ root

echo "Copying files to _build/html for deployment..."

if [ ! -d "_build/html" ]; then
    echo "Error: _build/html does not exist. Run 'jupyter book build --html' first."
    exit 1
fi

# Copy JSON data files from public/
cp public/divisions_flat.json _build/html/divisions_flat.json
cp public/countries.json _build/html/countries.json
cp public/urban_areas.json _build/html/urban_areas.json

# Copy query builder HTML from root
cp query_builder.html _build/html/query_builder.html

echo "✓ Files copied to _build/html/"
echo "  - divisions_flat.json (from public/)"
echo "  - countries.json (from public/)"
echo "  - urban_areas.json (from public/)"
echo "  - query_builder.html (from root)"
echo ""
echo "Done! Ready for deployment."
